### ISSUE TITLE
Aux connection issue "Unable to extract type character"

### ISSUE THREAD

**Issue by Tercioo** [polserver/polserver#106]
pol 2019-12-18
The .php and the .src for the test is attached into this issue. The test case is a php file that connects to pol aux and send two change password requests one after the other.

**What's the current behavior and steps to reproduce (1)**:
- fsockopen() from a php file on the pol's aux port.
- Then the the data to send using MuadDib's "POL Pack/Unpack Include file for PHP" version 11/26/2008.

> $command = packPolVar(array("change_password", "admin", "z"));
> $command .= "\n\r";
> fwrite($fp, $command);

And print the returned value:

> $response = fgets($fp, 2048);
> $response = unpackPolVar($response);
> ?><BR>POL Returned: <?PHP
> print_r ($response);

On Pol Console I have these lines of debug:

![polaux1](https://user-images.githubusercontent.com/9000280/71450443-d5686400-2740-11ea-906c-051d94c9269d.png)

The password does change, but it seems to be creating a second worker, maybe for 'connection.transmit()' the result or php's fgets() call is creating a worker as it doesn't send a message (and then "unable to extract type character") or maybe for the second fwrite() call (the php file sends two 'change password' with fwrite().

The thing is, if the second call to change the password is removed, pol prints the same thing which leads to a second worker being created for fgets() or 'connection.transmit()', using two change passwords request, the second call seems to be ignored (due the lack of another set of messages in the pol's console).

**What's the expected behavior?**:
The php connects to aux, send the first password change, the script execute the order and return to php; php then send the second password change request, the script execute on pol and return the result again.

[aux_issue_test_case.zip](https://github.com/polserver/polserver/files/4000838/aux_issue_test_case.zip)

**Comment by nogu3ira** [comment]
This occurred after some changes in Aux. I suggest going back to commit [23b0789](https://github.com/polserver/polserver/commit/23b07891d8cfc7a42aeed21495a3070340b9bdd2) from May 9, 2019 until it is fixed.

**Comment by nogu3ira** [comment]
Fixed. #111

**Comment by Tercioo** [comment]
thank you!
