### ISSUE TITLE
Crash while near the map canvas limit on Tokuno (polserver\lib\StackWalker\StackWalker.cpp : 1046)

### ISSUE THREAD

**Issue by Tercioo** [polserver/polserver#108]
Context: i was "walking" with .tele over the seas in tokuno realm, got a crash when approaching the map limits, for example 1439 1341 -2, teleporting (.tele) at random near this location or using a boat makes the pol crash.

POL100 Never Gonna Give You Up (Windows 64bit (Rev. c2a12fb8f)) compiled on Dec 18 2019 16:33:00.

##########################################################
Current StackBackTrace
StackWalker::ShowCallstack - 0x7ff7cfe6bdb7
  D:\GitHub\polserver\lib\StackWalker\StackWalker.cpp : 1046
Pol::Clib::HiddenMiniDumper::TopLevelFilter - 0x7ff7cfe4fc47
  D:\GitHub\polserver\pol-core\clib\mdump.cpp : 195
UnhandledExceptionFilter - 0x7ffa6c95f67a
  (filename not available)
memset - 0x7ffa6f5c4af2
  (filename not available)
_C_specific_handler - 0x7ffa6f5ac6d6
  (filename not available)
_chkstk - 0x7ffa6f5c11ff
  (filename not available)
RtlRaiseException - 0x7ffa6f58a289
  (filename not available)
KiUserExceptionDispatcher - 0x7ffa6f5bfe6e
  (filename not available)
Pol::Plib::InMemoryMapServer::GetMapCell - 0x7ff7cfe5bd33
  D:\GitHub\polserver\pol-core\plib\inmemorymapserver.cpp : 39
Pol::Plib::MapServer::GetMapShapes - 0x7ff7cfe59588
  D:\GitHub\polserver\pol-core\plib\mapserver.cpp : 113
Pol::Realms::Realm::walkheight - 0x7ff7cfd3cbd9
  D:\GitHub\polserver\pol-core\pol\realms\realmfunc.cpp : 365
Pol::Core::move_character_to - 0x7ff7cfbf22fc
  D:\GitHub\polserver\pol-core\pol\core.cpp : 68
Pol::Module::UOExecutorModule::internal_MoveCharacter - 0x7ff7cfcd1266
  D:\GitHub\polserver\pol-core\pol\module\uomod4.cpp : 115
Pol::Module::UOExecutorModule::mf_MoveObjectToLocation - 0x7ff7cfcd1f93
  D:\GitHub\polserver\pol-core\pol\module\uomod4.cpp : 65
Pol::Bscript::Executor::execFunc - 0x7ff7cfe0be49
  D:\GitHub\polserver\pol-core\bscript\executor.cpp : 841
Pol::Bscript::Executor::ins_func - 0x7ff7cfe154c3
  D:\GitHub\polserver\pol-core\bscript\executor.cpp : 2273
Pol::Bscript::Executor::execInstr - 0x7ff7cfe0c723
  D:\GitHub\polserver\pol-core\bscript\executor.cpp : 2994
Pol::Core::ScriptScheduler::run_ready - 0x7ff7cfc193a4
  D:\GitHub\polserver\pol-core\pol\globals\script_internals.cpp : 196
Pol::Core::step_scripts - 0x7ff7cfd4bc6b
  D:\GitHub\polserver\pol-core\pol\scrsched.cpp : 118
Pol::Core::scripts_thread - 0x7ff7cfd1b00d
  D:\GitHub\polserver\pol-core\pol\pol.cpp : 592
Pol::threadhelp::run_thread - 0x7ff7cfe4c106
  D:\GitHub\polserver\pol-core\clib\threadhelp.cpp : 118
Pol::threadhelp::thread_stub2 - 0x7ff7cfe4c3ef
  D:\GitHub\polserver\pol-core\clib\threadhelp.cpp : 178
thread_start<unsigned int (__cdecl*)(void *),1> - 0x7ff7cfec2020
  minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 97
BaseThreadInitThunk - 0x7ffa6d717bd4
  (filename not available)
RtlUserThreadStart - 0x7ffa6f58ced1
  (filename not available)
##########################################################
[12/26 22:23:38] ##########################################################
Unhandled Exception! Writing Minidump file. 
Post this file with explanation and last lines from log files on http://forums.polserver.com/tracker.php for the development team.
Saved dump file to '20191226221823-0.dmp'

Last function called: MoveObjectToLocation.

Dump file:
[20191226221823-0.zip](https://github.com/polserver/polserver/files/4003792/20191226221823-0.zip)

**Comment by Admin-Yukiko** [comment]
I can confirm this issue. I scripted boat movement around it a long time ago but if you are tete-ing it is a problem.

**Comment by Tercioo** [comment]
I'm 99% sure it's happening with boats, I'll try get a dump as well.

------ Original Message ------

**Comment by Tercioo** [comment]
Got crashes with a boat, the context is: navigating with a boat (Graphic 0x14F2, Shiptype 24624) near the bottom end of the map, was going forward and told the boat to straight right/left. I didn't move my character at any point.

The crash seems to be at random, majority of the times I just get a hit in an invisible wall.
There's a photo with coords where the crash happened, tried to replicate on the same location, no luck.

Best guest is, as the back trace is the same from .tele, maybe is something with Pol teleporting the player after the boat movement is done.

Stuff attached:
[pol100_Rev_c2a12fb8f(2019-12-18)_boat_crashes.zip](https://github.com/polserver/polserver/files/4004196/pol100_Rev_c2a12fb8f.2019-12-18._boat_crashes.zip)

**Comment by KevinEady** [comment]
Confirmed, still an issue on 35d16b8e5d536b349cfa45d3ab07a845f7b4c35c 

<img width="1688" alt="image" src="https://github.com/polserver/polserver/assets/8634912/047e8a45-21c6-4338-b20d-e7f19c7cb7d3">

**Comment by KevinEady** [comment]
Fixed via #634
