### ISSUE TITLE
POL infinite loop threads

### ISSUE THREAD

**Issue by Skinny1001** [polserver/polserver#11]
@gtozzi  This problem has occurred with some frequency.
Somehow, the POL enters an infinite loop in the thread and allows no one more connect to the game (stop in 'Verifying game').

This occurs:
http://i.imgur.com/fdkuUhP.png

I try to close correctly using Ctrl + C, but it is waiting, waiting, loops back and does not end the program. The only way is to kill the process, generating not the saving of the data.

Look when I try to close using with Ctrl + C:
http://i.imgur.com/mgbqgtc.png

The last script in use I saw was the Runner.ecl, but every time he does the loop (every 10 or 15 seconds), the PC changes.

See:
http://i.imgur.com/JI8vcHY.png

Thanks in advance.

**Comment by frozenblit** [comment]
What is the UseSingleThreadLogin value?

**Comment by Skinny1001** [comment]
@frozenblit the 'UseSingleThreadLogin' line doesn't exists in my pol.cfg file. So, this is using default value 0.

**Comment by frozenblit** [comment]
How often does that happen? Could you enable the singlethreadlogin and see if it stops?

**Comment by Skinny1001** [comment]
@frozenblit This specific problem occurred on the following dates:
September 11, 2015
September 15, 2015
November 5, 2015
December 3, 2015
December 19, 2015
February 9, 2016
February 16, 2016

Ok. I'll enable the singlethreadlogin. But, next week I'll be migrating the POL for linux. Can I must enable anyway?

**Comment by frozenblit** [comment]
It wouldn't hurt to try. The deadlock I mentioned on the boards is very rare, just like the one you described here. If it happens again on Windows, you can right click on pol.exe in the Task Manager and start a memory dump from there so we can know what the core was waiting for.

**Comment by Skinny1001** [comment]
@frozenblit Ok. I'll do.

**Comment by Skinny1001** [comment]
The bug has been fixed.
