### ISSUE TITLE
Compilation on linux -  ubuntu

### ISSUE THREAD

**Issue by vtajzich** [polserver/polserver#13]
Hi,

I cloned master, uncompressed boost and run ./build_linux.sh. During compilation I got:

`pol-core/clib/clib_MD5.cpp:119:105: fatal error: MD5.h: No such file or directory`

I created dockerfile to reproduce it: [dockerfile](https://gist.github.com/vtajzich/44b424476c1de0668d02)

**Comment by turleypol** [comment]
Looks like you don't have libssl-dev installed which ships the md5.h

**Comment by vtajzich** [comment]
@turleypol thanks!
