### ISSUE TITLE
Orc Galleon Mast collision

### ISSUE THREAD

**Issue by Pumpk1ns** [polserver/polserver#151]
The mast pieces of the Orc Galleon is colliding with terrain because it goes beyond the hull.
It makes this galleon less enjoyable to have since it doesn't fit some small harbors and is very annoying to manobrate or to find a good sport to "park".
You are always farway from the shore what makes it hard to leave the ship because of the distance. On my shard the distance to enter and leave the ship is limited to avoid abuse.

All Orc Galleon mast pieces share the same flags.
**Flags: Foliage, PartialHue**
Only the main Mast (e.g. **0x77CC**) have one more flag.
**Flags: Impassable, Foliage, PartialHue**

I'm not sure but maybe it would be possible to ignore collision for boat pieces that have the flag Foliage only, without impassable or surface.

E.g.: 
If boat piece has flags **foliage** and/or impassable, surface. Add collision.
if boat piece has flag **foliage** _WITHOUT_ impassable, surface. Don't add collision.
Maybe it is enough to only check for foliage flag and if it has then don't add the consilion. I think all ships items with foliage are not that significant for collision and will not cause new problems.

![newanvil](https://user-images.githubusercontent.com/46279173/84882916-39386d80-b090-11ea-8b85-9d3bdc623cb3.gif)

**Comment by KevinEady** [comment]
Hi @Pumpk1ns ,

Been working on this a bit... I have managed to mark items passable if "foliage and not impassable", and seems to work well. One thing I noticed during testing is that boat sails may get "intermixed":

<img width="464" alt="image" src="https://github.com/polserver/polserver/assets/8634912/56bbefd7-d63f-4beb-a7a2-9a1eda638837">

Not sure if this is something we want to allow, but not sure how to make explicit exceptions for this.

**Comment by KevinEady** [comment]
Fixed via https://github.com/polserver/polserver/pull/640
