### ISSUE TITLE
Add `struct enum` construct to Escript

### ISSUE THREAD

**Issue by KevinEady** [polserver/polserver#152]
Currently, enums are really just "grouped constants". We propose a new type, `struct enum`, which behaves as a _read-only struct_:

```
enum struct Days
    Sunday := 1,
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
endenum
```

```
var x = Days; // okay
var y = x.Monday; // okay
y = 0; // okay, you are changing the reference of `y`
x.Monday = 0; // no-op, `x` is a `struct enum`
Days.Monday = 0; // no-op, `Days` is a `struct enum`
```

`Days` is a struct and you can `Print(Days)`, and normal member accessors work (with `.` and `[]`)

```
Days[3] == Days.Tuesday
```

**Comment by Admin-Yukiko** [comment]
I like the C++ syntax for referencing enums.
enum COLORS
         RED := "red",
        BLUE := "blue",
        GREEN := "green ",
endenum

Print( COLORS::BLUE );

**Comment by KevinEady** [comment]
Nope.
