### ISSUE TITLE
CheckSkill not accepting attribute id.

### ISSUE THREAD

**Issue by sigmantium** [polserver/polserver#155]
From @DavidJSGardner
So, this is a feature request, one that I already thought was in place based on what the docs for CheckSkill say. I am talking primarily about one parameter, the skillid parameter.
`CheckSkill( character, skillid, difficulty, points )
Parameters:
Name 	Type
character 	Character Ref
skillid 	Integer skill/attribute ID
difficulty 	Integer skill use difficulty
points 	Integer skill gain on success`

Based on this entry, I went through every script on this shard that calls CheckSkill (and there are over 200 of them) and replaced the SKILLID_BLAHBLAH with the attribute ID. I mean, how fantastic, things can be unified and use attribute ids. So I spent a few hours trying to figure out why I was failing in a skill I had no business in failing in. I had assumed that the docs were correct because if you look at the docs for POL 95, POL 96, POL 97, POL 98, POL 99, POL 100, the entry for the skill parameter says Integer skill/attribute ID. I am being sent back Invalid parameter type. Expected param 1 as Integer, got String.

So in an effort to not have wasted countless hours moving skill ids over to attribute ids because the docs were misleading or changed in anticipation but the change never happened or <insert another reason here>, can we change CheckSkill to accept either a skill id or an attribute id?

**Comment by AsYlum-** [comment]
Isn't this already fixed https://github.com/polserver/polserver/commit/d040f0f34812aa96a347b1a79327944bb70e9df2 ?

**Comment by frozenblit** [comment]
Someone forgot ;) Support for attribute name added in #173.
