### ISSUE TITLE
Item creation not using Quality property from descriptor

### ISSUE THREAD

**Issue by Mr-Turing** [polserver/polserver#158]
When creating an item using a descriptor from GetItemDescriptor() and changing the Quality, CreateItemInBackpack() and CreateItemInContainer() are ignoring the descriptor Quality and using the original itemdesc.cfg value:
![image](https://user-images.githubusercontent.com/4960732/87499435-a825c980-c630-11ea-9a66-91684b3a3519.png)
![image](https://user-images.githubusercontent.com/4960732/87499465-c25fa780-c630-11ea-9a37-06819bd106cc.png)
result:
![image](https://user-images.githubusercontent.com/4960732/87499924-b7f1dd80-c631-11ea-8cb6-238917f74917.png)
![image](https://user-images.githubusercontent.com/4960732/87499934-bfb18200-c631-11ea-961b-abca68e0f6eb.png)

Tested with the latest nightly version.
Thanks for you time!

**Comment by KevinEady** [comment]
Hi @Mr-Turing ,

This should now be addressed in the most recent PR merge. Feel free to test it out!

Thanks, Kevin
