### ISSUE TITLE
Warning bug in eCompile, with verbosity set to 10.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#185]
Should verbosity=10 generate a warning for this?
return item.graphic := item.objtype;
and this?
return result := GFSendGump(who, virtue_gump);
**Warning! possible incorrect assignment.**
Ok. I changed return result := GFSendGump(who, virtue_gump); to
result  := GFSendGump(who, virtue_gump);
return result;
and I get the same error. It is as if eCompile has the file cached. The script is in the Distro in \pkg\systems\virtue\virtueGump.src, Line 187.

**Comment by KevinEady** [comment]
Not relevant with new compiler.
