### ISSUE TITLE
Antlr branch - apparently the 2020 compiler doesn't recognize the keyowrd 'unused'.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#192]
Error reported by the compiler:
**D:\GitHub\OriginModernDistro\pkg\mobiles\npcs\job\job.src:175:28: error: extraneous input 'unused' expecting IDENTIFIER
D:\GitHub\OriginModernDistro\pkg\mobiles\npcs\job\job.src:175:49: error: extraneous input 'unused' expecting IDENTIFIER
D:\GitHub\OriginModernDistro\pkg\mobiles\npcs\job\job.src: 2 errors, 0 warnings.**

The line in question:
**function GetJobType (byref unused player, byref unused merchant)**
Perhaps it is the placement of 'unused'? I will try before 'byref'.

**Comment by Admin-Yukiko** [comment]
Nope. Moving the 'unused' before 'byref' causes the compiler to report 'byref' as an error.

**Comment by eric-swanson** [comment]
Thanks!  The grammar was set up to accept either `byref` or `unused`, but not both.

Updated the grammar to accept either/both `byref` and `unused`, in that order, same as the original compiler.
