### ISSUE TITLE
extobj.cfg - missing intrinsic shield member

### ISSUE THREAD

**Issue by AsYlum-** [polserver/polserver#194]
In config/extobj.cfg we have Wrestling intrinsic weapon objtype. POL requires also intrinsic shield but that one is not defined in extobj.cfg. 

Looks like a bug because POL won't start if intrinsic shield objtype is not defined in itemdesc.cfg

```
Armor 0x1F022
{
    Name            intrinsicshield
    Graphic         1
    MaxHP           1
    SaveOnExit      0
}
```

**Comment by frozenblit** [comment]
You don't even need `config/extobj.cfg` as long as you're ok with the default objtypes. Nevertheless, Shield is already there:

https://github.com/polserver/polserver/blob/a5f22fe583ae96b39cbbeff88bab994c3feb2144/pol-core/support/extobj.cfg#L16

(Note: POL loads from `extobj.local.cfg` if it's there - I forgot about that one. The only other with a `.local.cfg` is `servspecopt.cfg`.)

**Comment by AsYlum-** [comment]
I didn't know that there is local version for some cfg. Good news. Looks like maybe I haven't overwritten old extobj.cfg from previous pol version and that's why Shield was missing. .

Looks like all is fine and this issue can be closed.

**Comment by frozenblit** [comment]
No problem. Thanks for reporting anyway. 👍
