### ISSUE TITLE
Wearable Items & corpses

### ISSUE THREAD

**Issue by rlka** [polserver/polserver#29]
NPC with a human graphic has wearable items in his backpack (but not equipped!).
When NPC dies these items are equipped on his corpse.

Did not tested it with Player Characters atm, will do it later.

**Comment by rlka** [comment]
Tested it with player character - same bug.

**Comment by KevinEady** [comment]
Issue present (still) on 35d16b8e5d536b349cfa45d3ab07a845f7b4c35c

**Comment by KevinEady** [comment]
This seems to be explicitly designed this way: when a player dies, we move the items to the corpse using this function:

https://github.com/polserver/polserver/blob/35d16b8e5d536b349cfa45d3ab07a845f7b4c35c/pol-core/pol/mobile/corpse.cpp#L47-L57

We explicitly check if the item is equippable, and if there is no already equipped item on that layer. If both are true, we add the item to its specific layer.

Will review with team if this is the intended functionality.

**Comment by rlka** [comment]
Seems like it's was just a fastest solution, long time ago :)
It was a long time ago but i found this bug in a hard way - light sources also have layer, and server crashed is someone had a lamp in a backpack :D 
Lightsources bug is already fixed, but this here is actually source of problem
