### ISSUE TITLE
Clarify line number in error output.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#339]
```
Compiling: D:/GitHub/OriginModernDistro/pkg/systems/cleric/rites/Level7/earthquake.src
D:\GitHub\OriginModernDistro\pkg\systems\cleric\rites\Level7\earthquake.src:44:5: error: User Function 'ApplyRawDamageExg' not found.
```
In the above example, the line on which the error was encountered is not easily identifiable. Perhaps something like
`D:\GitHub\OriginModernDistro\pkg\systems\cleric\rites\Level7\earthquake.src: - Line 44:5: error: User Function 'ApplyRawDamageExg' not found.`

**Comment by KevinEady** [comment]
It is common practice to have a location in a file specified as `<file>:<line>:<column>`. Editors can use this format to "jump to location" when eg. clicked.
