### ISSUE TITLE
DestroyItem(multi.serial); crashes Pol

### ISSUE THREAD

**Issue by Pumpk1ns** [polserver/polserver#348]
### Issue:

I placed a multi and by mistake used **_DestroyItem(multi.serial);_**, it destroys the multi but after that Pol crashes. :p

```
use uo;
use os;

program CrashPol( chr )

    var boat := CreateMultiAtLocation( chr.x, chr.y, chr.z, 0x1234, CRMULTI_IGNORE_ALL, chr.realm );
    Sleep(3);
    DestroyItem (boat.serial);

endprogram
```

> [11/09 12:11:35] remove_item_from_world: item 0x400CC137 at 807,100 does not exist in world zone ( Old Serial: 0x400CC137 )
> [11/09 12:11:35] Assertion Failed: itr != zone.items.end(), ..\pol-core\pol\uworld.cpp, line 62
> [11/09 12:11:35] Forcing stack backtrace.

The same thing happens with house multis.
It removes the multi, but leaves the components there and then crashes.
If I removed the **.serial** from **DestroyItem (multi.serial);** the crash doesn't happens. No crash and the multi doesn't get destroyed.

### This might be the problem:

> it's a trick in getItemParam
> if ( ( aob != nullptr ) && ( aob->object_type() == &eitemrefobjimp_type ) )
> I think it's from this check of aob->object_type()

-Text quoted from discord chat.

**Comment by KevinEady** [comment]
Fixed in https://github.com/polserver/polserver/pull/506
