### ISSUE TITLE
Packet 0x8D docs mistake

### ISSUE THREAD

**Issue by coreuo** [polserver/polserver#349]
There is a mistake in [https://docs.polserver.com/packets/index.php?Packet=0x8D](https://docs.polserver.com/packets/index.php?Packet=0x8D):

- BYTE[2] beard style
- BYTE[2] beard color

It should be:

- BYTE[2] beard color
- BYTE[2] beard style

Packet docs helped me a lot, so many thanks for them.

**Comment by frozenblit** [comment]
Thanks for noticing it! It's fixed now. POL already had the correct order.
