### ISSUE TITLE
Wrong line number when reporting missing semicolon.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#350]
The compiler reports the line number following the offending line.
Example:
line 5  var fred := "Fred"
line 6  var wilma := "Wilma";

The compiler will report line 6 missing a semicolon.

**Comment by KevinEady** [comment]
Unfortunately this is how ANTLR handles errors when parsing sources. It is reporting line 6 as errored because that is the last place the semicolon _could_ be in order to have a successful parse:
```
var fred := "Fred"
;var wilma := "Wilma";
```
