### ISSUE TITLE
linker error compiling on last arch linux

### ISSUE THREAD

**Issue by simona70** [polserver/polserver#373]
[100%] Linking CXX executable ../../../bin/pol
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(easy.c.o): in function `curl_global_init':
easy.c:(.text+0x85): undefined reference to `libssh2_init'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(easy.c.o): in function `curl_global_init_mem':
easy.c:(.text+0x199): undefined reference to `libssh2_init'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(easy.c.o): in function `curl_easy_init':
easy.c:(.text+0x288): undefined reference to `libssh2_init'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(easy.c.o): in function `curl_global_cleanup':
easy.c:(.text+0x1f8): undefined reference to `libssh2_exit'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(version.c.o): in function `curl_version.part.0':
version.c:(.text+0x88): undefined reference to `libssh2_version'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `ssh_statemach_act':
ssh.c:(.text+0x6f1): undefined reference to `libssh2_session_set_blocking'
/bin/ld: ssh.c:(.text+0x70c): undefined reference to `libssh2_session_handshake'
/bin/ld: ssh.c:(.text+0x74c): undefined reference to `libssh2_hostkey_hash'
/bin/ld: ssh.c:(.text+0x80e): undefined reference to `libssh2_session_hostkey'
/bin/ld: ssh.c:(.text+0x885): undefined reference to `libssh2_knownhost_checkp'
/bin/ld: ssh.c:(.text+0x967): undefined reference to `libssh2_userauth_list'
/bin/ld: ssh.c:(.text+0xaa1): undefined reference to `libssh2_channel_free'
/bin/ld: ssh.c:(.text+0xae3): undefined reference to `libssh2_session_disconnect_ex'
/bin/ld: ssh.c:(.text+0xb7a): undefined reference to `libssh2_channel_send_eof'
/bin/ld: ssh.c:(.text+0xc12): undefined reference to `libssh2_scp_send64'
/bin/ld: ssh.c:(.text+0xc86): undefined reference to `libssh2_channel_free'
/bin/ld: ssh.c:(.text+0xcd9): undefined reference to `libssh2_sftp_close_handle'
/bin/ld: ssh.c:(.text+0xd08): undefined reference to `libssh2_sftp_shutdown'
/bin/ld: ssh.c:(.text+0xd8d): undefined reference to `libssh2_sftp_unlink_ex'
/bin/ld: ssh.c:(.text+0xe75): undefined reference to `libssh2_sftp_rmdir_ex'
/bin/ld: ssh.c:(.text+0xf06): undefined reference to `libssh2_sftp_rename_ex'
/bin/ld: ssh.c:(.text+0xf2f): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0xfb7): undefined reference to `libssh2_sftp_mkdir_ex'
/bin/ld: ssh.c:(.text+0xfe4): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x110f): undefined reference to `libssh2_sftp_close_handle'
/bin/ld: ssh.c:(.text+0x11e8): undefined reference to `libssh2_agent_list_identities'
/bin/ld: ssh.c:(.text+0x1236): undefined reference to `libssh2_agent_get_identity'
/bin/ld: ssh.c:(.text+0x12f6): undefined reference to `libssh2_sftp_init'
/bin/ld: ssh.c:(.text+0x1347): undefined reference to `libssh2_sftp_symlink_ex'
/bin/ld: ssh.c:(.text+0x13d0): undefined reference to `libssh2_sftp_statvfs'
/bin/ld: ssh.c:(.text+0x145b): undefined reference to `libssh2_sftp_symlink_ex'
/bin/ld: ssh.c:(.text+0x1488): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x1510): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x1624): undefined reference to `libssh2_sftp_mkdir_ex'
/bin/ld: ssh.c:(.text+0x1774): undefined reference to `libssh2_sftp_readdir_ex'
/bin/ld: ssh.c:(.text+0x18ab): undefined reference to `libssh2_sftp_symlink_ex'
/bin/ld: ssh.c:(.text+0x1a4f): undefined reference to `libssh2_sftp_stat_ex'
/bin/ld: ssh.c:(.text+0x1a7c): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x1b8b): undefined reference to `libssh2_userauth_publickey_fromfile_ex'
/bin/ld: ssh.c:(.text+0x1be9): undefined reference to `libssh2_session_last_error'
/bin/ld: ssh.c:(.text+0x1c7a): undefined reference to `libssh2_sftp_close_handle'
/bin/ld: ssh.c:(.text+0x1dc5): undefined reference to `libssh2_scp_recv2'
/bin/ld: ssh.c:(.text+0x1e81): undefined reference to `libssh2_sftp_open_ex'
/bin/ld: ssh.c:(.text+0x1ecc): undefined reference to `libssh2_sftp_stat_ex'
/bin/ld: ssh.c:(.text+0x1fc6): undefined reference to `libssh2_userauth_password_ex'
/bin/ld: ssh.c:(.text+0x2089): undefined reference to `libssh2_userauth_keyboard_interactive_ex'
/bin/ld: ssh.c:(.text+0x20f5): undefined reference to `libssh2_knownhost_free'
/bin/ld: ssh.c:(.text+0x2115): undefined reference to `libssh2_agent_disconnect'
/bin/ld: ssh.c:(.text+0x2134): undefined reference to `libssh2_agent_free'
/bin/ld: ssh.c:(.text+0x215c): undefined reference to `libssh2_session_free'
/bin/ld: ssh.c:(.text+0x22fd): undefined reference to `libssh2_sftp_stat_ex'
/bin/ld: ssh.c:(.text+0x23fe): undefined reference to `libssh2_sftp_open_ex'
/bin/ld: ssh.c:(.text+0x2483): undefined reference to `libssh2_sftp_seek64'
/bin/ld: ssh.c:(.text+0x2502): undefined reference to `libssh2_channel_wait_eof'
/bin/ld: ssh.c:(.text+0x253d): undefined reference to `libssh2_channel_wait_closed'
/bin/ld: ssh.c:(.text+0x25cc): undefined reference to `libssh2_sftp_stat_ex'
/bin/ld: ssh.c:(.text+0x25f9): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x26bd): undefined reference to `libssh2_sftp_seek64'
/bin/ld: ssh.c:(.text+0x2850): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x2871): undefined reference to `libssh2_session_last_error'
/bin/ld: ssh.c:(.text+0x2a31): undefined reference to `libssh2_agent_connect'
/bin/ld: ssh.c:(.text+0x2a9c): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x2c62): undefined reference to `libssh2_agent_userauth'
/bin/ld: ssh.c:(.text+0x2dad): undefined reference to `libssh2_sftp_stat_ex'
/bin/ld: ssh.c:(.text+0x2eb2): undefined reference to `libssh2_sftp_open_ex'
/bin/ld: ssh.c:(.text+0x2f8f): undefined reference to `libssh2_userauth_authenticated'
/bin/ld: ssh.c:(.text+0x305e): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x3073): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x30d4): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x30f5): undefined reference to `libssh2_session_last_error'
/bin/ld: ssh.c:(.text+0x3135): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x318a): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x31d7): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x3282): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x3413): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x34fc): undefined reference to `libssh2_knownhost_add'
/bin/ld: ssh.c:(.text+0x3527): undefined reference to `libssh2_knownhost_writefile'
/bin/ld: ssh.c:(.text+0x3704): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x3783): undefined reference to `libssh2_agent_init'
/bin/ld: ssh.c:(.text+0x37cd): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x380c): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x3b3e): undefined reference to `libssh2_session_last_errno'
/bin/ld: ssh.c:(.text+0x3b53): undefined reference to `libssh2_sftp_last_error'
/bin/ld: ssh.c:(.text+0x3d31): undefined reference to `libssh2_sftp_seek64'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `scp_send':
ssh.c:(.text+0x4086): undefined reference to `libssh2_channel_write_ex'
/bin/ld: ssh.c:(.text+0x40b8): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `ssh_block_statemach.constprop.0':
ssh.c:(.text+0x4175): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `ssh_done':
ssh.c:(.text+0x4381): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `sftp_doing':
ssh.c:(.text+0x44e8): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `scp_doing':
ssh.c:(.text+0x4578): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o):ssh.c:(.text+0x4608): more undefined references to `libssh2_session_block_directions' follow
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `scp_recv':
ssh.c:(.text+0x4636): undefined reference to `libssh2_channel_read_ex'
/bin/ld: ssh.c:(.text+0x4660): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `sftp_send':
ssh.c:(.text+0x46aa): undefined reference to `libssh2_sftp_write'
/bin/ld: ssh.c:(.text+0x46d8): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `sftp_recv':
ssh.c:(.text+0x474a): undefined reference to `libssh2_sftp_read'
/bin/ld: ssh.c:(.text+0x47a0): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `ssh_connect':
ssh.c:(.text+0x4864): undefined reference to `libssh2_session_init_ex'
/bin/ld: ssh.c:(.text+0x4897): undefined reference to `libssh2_knownhost_init'
/bin/ld: ssh.c:(.text+0x48bb): undefined reference to `libssh2_knownhost_readfile'
/bin/ld: ssh.c:(.text+0x493e): undefined reference to `libssh2_session_flag'
/bin/ld: ssh.c:(.text+0x4988): undefined reference to `libssh2_session_block_directions'
/bin/ld: ../../../lib/curl-7.57.0/INSTALL/lib/libcurl.a(ssh.c.o): in function `ssh_do':
ssh.c:(.text+0x4ae8): undefined reference to `libssh2_session_block_directions'
collect2: error: ld returned 1 exit status
make[2]: *** [pol-core/pol/CMakeFiles/pol.dir/build.make:3668: ../bin/pol] Errore 1
make[1]: *** [CMakeFiles/Makefile2:994: pol-core/pol/CMakeFiles/pol.dir/all] Errore 2
make: *** [Makefile:182: all] Errore 2

**Comment by simona70** [comment]
solved adding -DCMAKE_USE_LIBSSH2=OFF to set(CURL_FLAGS -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF -DCURL_STATICLIB=ON -DBUILD_SHARED_LIBS=OFF -DCURL_DISABLE_LDAP=ON
-DCMAKE_USE_LIBSSH2=OFF) inside cmake/Curl.cmake

**Comment by KevinEady** [comment]
Hi @simona70 ,

Thanks for the info. This issue has spurred up conversation on Discord about how we want to change our CI build systems to build on different OSes in order to catch problems like this.

Would you be willing to submit a PR? This will allow us to see if it builds correctly on our CI using existing OSes.

**Comment by simona70** [comment]
I am available to provide what is necessary but I do not understand what is
needed. Information about my system such as hardware, software, operating
system, system updates, system libraries, etc?

---------------------------------------------------------------------------------------------------------------------------------------
Simona


Il giorno gio 25 feb 2021 alle ore 13:24 Kevin Eady <
notifications@github.com> ha scritto:
