### ISSUE TITLE
error running pol like "./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pol)"

### ISSUE THREAD

**Issue by simona70** [polserver/polserver#376]
on one debian install:

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pol)

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./pol)

on another debian install:

./pol: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./pol)

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pol)

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./pol)

./pol: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./pol)

on ubuntu 20.4 lts

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./pol)

./pol: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./pol)

but my command "file /usr/lib/x86_64-linux-gnu/libc.so.6" give:
/usr/lib/x86_64-linux-gnu/libc.so.6: symbolic link to libc-2.31.so

seems ok.
What is my error?

On arch Linux updated instead it's ok.

only on arch linux i have the last glibc installed.

**Comment by simona70** [comment]
solved.
I have compiled pol on ubuntu with come "fix" like
sudo apt install zlib1g-dev
sudo cp /home/uo/polserver-master/lib/zlib/zlib.h /usr/include/.
inside cmake/init.cmake
#if (NOT HAVE_ZLIB)
#  message(FATAL_ERROR "ZLib not found")
#endif()

and voila... pol done and no error.

**Comment by simona70** [comment]
on debian pol.ubuntu give error

./pol: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./pol)
./pol: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./pol)

(less the one upper but do not start)

must i compile under debian to compile under debian?

**Comment by simona70** [comment]
pol compiled on archlinux os ok only for archlinux
pol compiled on ubuntu 20.04-lts is ok only on ubuntu 20.4-lts

**Comment by simona70** [comment]
in case someone needs them at the end I have the compiled executables of the pol (but the pol forum doesn't work anymore?) as of 20-27 / 2/2021 with sources of the same period up to date:
- under archlinux with "gcc (GCC) 10.2.0"
- under unbuntu 20.04-lts with "gcc (Ubuntu 9.3.0-17ubuntu1 ~ 20.04) 9.3.0"
- under debian 11 with "gcc (Debian 10.2.1-6) 10.2.1 20210110"

**Comment by simona70** [comment]
i think batch to compile should be better :-)

**Comment by KevinEady** [comment]
IIRC, compiling POL on a machine will use that glibc version and will require that (or newer) on any machines running that executable. I don't think this is something we can address. Please re-open if you believe otherwise.
