### ISSUE TITLE
UO Sprites

### ISSUE THREAD

**Issue by LedLoaf** [polserver/polserver#402]
Hello,

This might be irrelevant, but I was wondering if anyone knows if it's possible to see all the sprites of UO? It has always interested me in how it is all laid out etc. If anyone knows how I can take a look at this I'd appreciate it. I'm assuming it's on the client side, but I didn't see anything I could physically look at.

Any help would be great.

**Comment by CWO333** [comment]
Look at the UO Fiddler project if you want to look over/edit the graphics

https://github.com/polserver/UOFiddler

**Comment by LedLoaf** [comment]
> Look at the UO Fiddler project if you want to look over/edit the graphics
> 
> https://github.com/polserver/UOFiddler

Will, do was just looking at it. Can the sprites actually be extracted? Checking it out, thanks.

**Comment by turleypol** [comment]
Not core related.
