### ISSUE TITLE
Feature Request: Surface the hash function used to hash passwords for use in eScript?

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#411]
I was thinking that it might be useful to be able to hash values from eScript.
function Hash(string_value_to_be_hashed) would return the hash value as a string.

**Comment by turleypol** [comment]
https://docs.polserver.com/pol100/fullfunc.php?xmlfile=polsysem#MD5Encrypt

Or am I missing something?

**Comment by frozenblit** [comment]
Complementing what @turleypol said, the hash in `accounts.txt` is `MD5Encrypt(acctname + password)`. 

Also, `acct.checkpassword(password)` returns true/false if the password is correct for that account. Maybe `checkpassword` fits your use case better?

**Comment by Admin-Yukiko** [comment]
How did I miss that? Thanks @turleypol
