### ISSUE TITLE
var myarray array; does not produce a compile error.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#427]
The following program compiles with no error and _does_ create an array named "myarray".

```
	var myarray array;
	Print(TypeOf(myarray));
	return;
```
When I substitute braces instead of "array" in the declaration, it returns an error.

**Comment by frozenblit** [comment]
From our discord discussion: 

- This is by design. The syntax for empty arrays is valid but deprecated since at least core 096. The deprecation warning was lost in the new compiler.

- It might be time to remove the feature altogether.

**Comment by KevinEady** [comment]
As designed.
