### ISSUE TITLE
mobile.client.connected crashes the shard.

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/polserver#451]
While I was writing a simple messaging dot command, I had a momentary lapse in memory and had forgotten that the connected member is not attached to client and had used the following code to determine if the player was online:
`
if( !mobile.client.connected )
SendSysMessage( mobile, "You cannot message this player.", 0x3, 0x32 );
return 0;
endif
`

When I had executed the command in game the shard crashed, it took me a few attempts to narrow down the problem in my code.

At any rate, this shouldn't cause the shard to crash.

**Comment by turleypol** [comment]
Should be fixed with #462
