### ISSUE TITLE
Storing gump in a datafile

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/polserver#483]
I am running into an issue whereby I am storing a gump in a datafile so that it can be recalled later, cached. 

It stores the gump fine and the gump is recalled fine UNTIL I restart the shard and try to recall the gump. When I print the datafile property a gump is stored in, I receive the following print out:
`struct{ base = struct{ CloseLoc = 0, DisposeLoc = 1, height = 0, MoveLoc = 2, width = 0, x = 100, y = 50 }, cur_page = 1, data = { <DIV ALIGN=CENTER>Welcome, error{ errortext = "Unable to unpack string length. String length excessive." }, error{ errortext = "Unable to extract type character" }, error{ errortext = "Unable to extract type character" } } }`

These gumps utilize html elements and there is quite a bit of text in them, there is not an issue storing the gumps as when I do a string search of the datafile, I do not see any errortext and as stated, the gumps read back just fine up until the point I restart the shard and try to read the gump back in post restart.

Attached is the datafile in question for inspection purposes.
[gumps.1.txt](https://github.com/polserver/polserver/files/9899336/gumps.1.txt)

**Comment by frozenblit** [comment]
Issue was discussed on Discord and had to do with newlines in strings, which are not supported by the CProp serialization format. Workarounds include using XML, storing newlines as arrays or converting the newline character.
