### ISSUE TITLE
Feature Request: Snooping

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/polserver#489]
I've posted about this on the [forums](https://forums.polserver.com/viewtopic.php?f=54&t=6443) and discussed this in Discord but thought it might be worth posting here to maybe get some traction. 

New Core Item: SnoopingContainer
New Function: SendSnoopingContainer( mobile, container )
New Script Type: Snooping.src

The New Core Item:
The SnoopingContainer would allow for CanInsert, OnInsert, CanRemove, OnRemove scripts to be assigned to it that would be different than the main script types typically assigned to a backpack. Ideally it would be nice if a new class could be added for this item as well to allow access to the following members: (I can't think of any methods that would be necessarily handy except maybe Close() but I suspect the SendSnoopingContainer would work similar to the SendOpenSpecialContainer function, closes on character move).
Owner - owner of the backpack being snooped
SnoopedAt - game clock when the backpack was snooped (not necessary I suppose but could be handy.)

I suppose it would be nice if the container closes when either player moves more than X tiles from each other but this could be handled script side if need be.

The New Function:
SendSnoopingContainer would send the victim's backpack but honoring the CanInsert, OnInsert, CanRemove, OnRemove scripts assigned to the new SnoopingContainer object.

The New Script Type:
Lives in /scripts/misc/ only.
If present, when a player double clicks on the backpack of another player, this script is fired. If this script is not present, the core behaves as it does now, dropping the double click packet altogether.

An example of the code for this script would be as follows:
`
use uo;
use os;

program snooping_script( mobile, victim )

if( mobile.cmdlevel < victim.cmdlevel )
SendSysMessage( mobile, "I don't think so bub. );
return 0;
endif

if( mobile.cmdlevel >= 3 )
SendOpenSpecialContainer( mobile, victim.backpack );
else
// Should do some snooping skill check here...
SendSnoopingContainer( mobile, victim.backpack );
endif

return 1;
endprogram
`

The following would be nice to have as well but maybe not necessary
New Members for Character: snooping_from
snooping_from would return an array of characters the player is currently snooping from, the player is added to the list when SendSnoopingContainer function is successfully sent to the player.

This would allow for us to check the range of the snooper from the victim in the container based scripts assigned to the SnoopingContainer item. 

This is kind of a WiP idea and wouldn't mind discussing this further here so it is not lost in the weeds of discord channels.

**Comment by KevinEady** [comment]
Fixed by #491 and #493
