### ISSUE TITLE
Configurable View Range

### ISSUE THREAD

**Issue by Zrnik** [polserver/polserver#545]
Hello, i have a request for a change that would make my life much easier, i have to build my own version of pol core because i want my client to allow 40 tiles visual range, which i have to change on those lines:

https://github.com/polserver/polserver/blob/eaa96e62dd25fa0df3b59c281150e34e986f80e5/pol-core/plib/uconst.h#L53
https://github.com/polserver/polserver/blob/eaa96e62dd25fa0df3b59c281150e34e986f80e5/pol-core/plib/uconst.h#L54

(and here for tests https://github.com/polserver/polserver/blob/eaa96e62dd25fa0df3b59c281150e34e986f80e5/testsuite/pol/testpkgs/house/test_houserange.src#L41 )

I am not very much into c++ ecosystem and compiling it by my self is pain (+ i want up 2 date core, so i have to merge your changes once a while)

This is actually the only change i have in my custom built core. 

I am not capable to achieve this myself in c++ (otherwise i would submit a pull request) so is there a posibility, that you would add configuration entry in `pol.cfg` for example that will set this visual range? 

`MaxClientVisualRange 40` for example?

Im willing to pay for this change.

**Comment by Pumpk1ns** [comment]
I like that idea. But are you sure that it doesn't cause strange side effects?

**Comment by Zrnik** [comment]
It would in regular client, I have also modified classicuo client that was updated to support the extended view range
