### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by renanzambrin** [polserver/polserver#55]
When I try to build on linux, i get this error

polserver/pol-core/clib/clib_MD5.cpp:124:10: fatal error: MD5.h: No such file or directory
 #include "MD5.h"

I taked a look in the code and there is no MD5.h in the clib folder.

**Comment by turleypol** [comment]
Please install libssl-dev the option without is more or less deprecated and did not work since years I think.
After the installation you need to execute
./build_tools.sh -p
To clean the cmake cache

**Comment by renanzambrin** [comment]
Thanks, @turleypol, you could add this lib to the readme with the zlib
