### ISSUE TITLE
ReloadConfiguration()

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/polserver#559]
Running the latest build of the core and [ReloadConfiguration()](https://docs.polserver.com/pol100/fullfunc.php?xmlfile=polsysem#ReloadConfiguration) seems to be crashing the shard.

The following simple script is where I call this function, it is my unloadall command, at first I thought it was another issue but alas, when I comment out ReloadConfiguration() and use the command, no crash, but when I uncomment it and use the command, crash time.

`
use os;
use uo;
use cfgfile;
use polsys;

program textcmd_unloadall( mobile )

	ReloadConfiguration();
	SendSysMessage( mobile, "Number of scripts unloaded: "+Unload_Scripts( "" ), 0x3, 0x65 );

	return 1;
endprogram
`

**Comment by turleypol** [comment]
Could you add a backtrace? Then it's easier for us to find the problem

**Comment by DavidJSGardner** [comment]
Sorry about that, here you be.

Unhandled Exception! Minidump started...

##########################################################
Current StackBackTrace
StackWalker::ShowCallstack - 0x7ff740235717
  F:\Repositories\polserver\lib\StackWalker\StackWalker.cpp : 1046
Pol::Clib::HiddenMiniDumper::print_backtrace - 0x7ff74021e25d
  F:\Repositories\polserver\pol-core\clib\mdump.cpp : 283
Pol::Clib::HiddenMiniDumper::TopLevelFilter - 0x7ff74021dd2c
  F:\Repositories\polserver\pol-core\clib\mdump.cpp : 196
UnhandledExceptionFilter - 0x7ffe062ae237
  (filename not available)
memset - 0x7ffe087354b0
  (filename not available)
_C_specific_handler - 0x7ffe0871ca06
  (filename not available)
_chkstk - 0x7ffe087323af
  (filename not available)
RtlRaiseException - 0x7ffe086e14b4
  (filename not available)
KiUserExceptionDispatcher - 0x7ffe08730ebe
  (filename not available)
Pol::Core::ExportScript::FindExportedFunction - 0x7ff740100c8b
  F:\Repositories\polserver\pol-core\pol\syshookscript.cpp : 74
Pol::Mobile::NPC::custom_script_method - 0x7ff74016524d
  F:\Repositories\polserver\pol-core\pol\uoscrobj.cpp : 3647
Pol::Module::ECharacterRefObjImp::call_polmethod - 0x7ff740164610
  F:\Repositories\polserver\pol-core\pol\uoscrobj.cpp : 220
Pol::Bscript::Executor::ins_call_method - 0x7ff7401e6393
  F:\Repositories\polserver\pol-core\bscript\executor.cpp : 2449
Pol::Bscript::Executor::execInstr - 0x7ff7401df75f
  F:\Repositories\polserver\pol-core\bscript\executor.cpp : 3078
Pol::Core::ScriptScheduler::run_ready - 0x7ff73ffa13e5
  F:\Repositories\polserver\pol-core\pol\globals\script_internals.cpp : 196
Pol::Core::step_scripts - 0x7ff7400e4cf5
  F:\Repositories\polserver\pol-core\pol\scrsched.cpp : 120
Pol::Core::scripts_thread - 0x7ff7400aec21
  F:\Repositories\polserver\pol-core\pol\pol.cpp : 594
Pol::threadhelp::run_thread - 0x7ff740219dd9
  F:\Repositories\polserver\pol-core\clib\threadhelp.cpp : 122
Pol::threadhelp::thread_stub2 - 0x7ff74021a0cf
  F:\Repositories\polserver\pol-core\clib\threadhelp.cpp : 182
thread_start<unsigned int (__cdecl*)(void *),1> - 0x7ff740275682
  minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 97
BaseThreadInitThunk - 0x7ffe08497344
  (filename not available)
RtlUserThreadStart - 0x7ffe086e26b1
  (filename not available)
##########################################################
##########################################################
Unhandled Exception! Writing Minidump file.
Post this file with explanation and last lines from log files on http://forums.polserver.com/tracker.php for the development team.
Saved dump file to '20231105215133-0.dmp'

Last Script: pkg/npcs\townfolk\merchants/merchant.ecl PC: 6286
##########################################################

**Comment by turleypol** [comment]
Fixed with #560
