### ISSUE TITLE
Fresh Install Fail

### ISSUE THREAD

**Issue by sigmantium** [polserver/polserver#61]
Just installed Windows 10 x64 on my laptop.
Fresh install of VS 2017 community
CMAKE seemed fine but building the solution i received:

```19>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:REF' specification
19>LINK : fatal error LNK1181: cannot open input file '..\..\..\cmake\..\lib\curl-7.57.0\builds\libcurl-x64-release-static\lib\libcurl.lib'
19>Done building project "pol.vcxproj" -- FAILED.```

**Comment by turleypol** [comment]
Can you check if only the folders are different in the lib/curl? It should independent of your build configuration build curl as release.

**Comment by KevinEady** [comment]
Hi @turleypol , I also had the same issue.

In my folder `polserver\lib\curl-7.57.0\builds\libcurl-x64-release-static\lib` it created the file `libcurl-d.lib` but not the one that's requested.

**Comment by turleypol** [comment]
And you both really use the lastest master revision? ;)
