### ISSUE TITLE
Feature request: Weight R/W prop, weight-reducing bags.

### ISSUE THREAD

**Issue by Reloecc** [polserver/polserver#631]
Hello, we'd be very pleased to present weight-reducing containers like quivers or specialized material chests to our players. As far as I know, there is no proper way of doing it. I was not successful in my tries of setting an item's weight when being added to the bag. And I have not found any props that would be helpful.

We have been able to offer virtual containers, but such leads to a bad UX. And also related systems, like razor agents, cuo counters or shooting system, need to be prepared for them, which is not the best scenario.

I've read the related discussions on your Discord channel (that lead back to the year 2018) and also on the old forum, dating from 2013. I've read that you've considered it and also planned it. Is 2024 the best year to make that dream come true? O:-)

Thank you.

**Comment by KevinEady** [comment]
Fixed in #633
