### ISSUE TITLE
POL crash 20151118155731

### ISSUE THREAD

**Issue by Skinny1001** [polserver/polserver#7]
pol.pdb, pol.exe and POL099-2013-09-03 Break Everything Even Rudder-20151118155731-0.dmp 
See the log:

[11/18 19:16:52] 
##########################################################
Current StackBackTrace
StackWalker::ShowCallstack - 0x140240a24
  d:\polserver\lib\stackwalker\stackwalker.cpp : 1047
Pol::Clib::HiddenMiniDumper::print_backtrace - 0x14023590f
  d:\polserver\pol-core\clib\mdump.cpp : 268
Pol::Clib::HiddenMiniDumper::TopLevelFilter - 0x140235534
  d:\polserver\pol-core\clib\mdump.cpp : 184
UnhandledExceptionFilter - 0x76fbb990
  (filename not available)
EtwEventSetInformation - 0x770ca0b8
  (filename not available)
_C_specific_handler - 0x77058008
  (filename not available)
RtlDecodePointer - 0x7706905d
  (filename not available)
RtlUnwindEx - 0x77058c0f
  (filename not available)
KiUserExceptionDispatcher - 0x7708d948
  (filename not available)
Pol::Bscript::BApplicObj<Pol::Module::ClientPtrHolder>::~BApplicObj<Pol::Module::ClientPtrHolder> - 0x14010c8c1
  (filename not available)
Pol::Module::EClientRefObjImp::`scalar deleting destructor' - 0x14010d1dc
  (filename not available)
Pol::Bscript::BObject::~BObject - 0x1401ec977
  d:\polserver\pol-core\bscript\object.cpp : 118
std::vector<Pol::Bscript::BObjectRef,std::allocator<Pol::Bscript::BObjectRef> >::_Destroy - 0x1400d4b1c
  d:\program files (x86)\microsoft visual studio 12.0\vc\include\vector : 1567
Pol::Bscript::Executor::ins_return - 0x1401ffc22
  d:\polserver\pol-core\bscript\executor.cpp : 2429
Pol::Bscript::Executor::execInstr - 0x1401f5788
  d:\polserver\pol-core\bscript\executor.cpp : 3219
Pol::Bscript::Executor::exec - 0x1401f4fc1
  d:\polserver\pol-core\bscript\executor.cpp : 3318
Pol::Core::ExportScript::call - 0x1400d5384
  d:\polserver\pol-core\pol\syshookscript.cpp : 204
Pol::Network::CallOutgoingPacketExportedFunction - 0x14016e760
  d:\polserver\pol-core\pol\network\packethooks.cpp : 201
Pol::Network::Client::transmit - 0x14016750e
  d:\polserver\pol-core\pol\network\clientio.cpp : 209
Pol::Network::ClientTransmitThread - 0x140067a2a
  d:\polserver\pol-core\pol\network\clienttransmit.cpp : 56
Pol::threadhelp::run_thread - 0x1402334d2
  d:\polserver\pol-core\clib\threadhelp.cpp : 122
Pol::threadhelp::thread_stub2 - 0x14023372d
  d:\polserver\pol-core\clib\threadhelp.cpp : 182
_callthreadstartex - 0x140267dd7
  f:\dd\vctools\crt\crtw32\startup\threadex.c : 376
_threadstartex - 0x140267f7e
  f:\dd\vctools\crt\crtw32\startup\threadex.c : 354
BaseThreadInitThunk - 0x76f35a4d
  (filename not available)
RtlUserThreadStart - 0x7706b831
  (filename not available)
##########################################################
[11/18 19:16:52] ##########################################################
Unhandled Exception! Writing Minidump file. 
Post this file with explanation and last lines from log files on http://forums.polserver.com/tracker.php for the development team.
Saved dump file to 'POL099-2013-09-03 Break Everything Even Rudder-20151118155731-0.dmp'

Last Script: pkg/server core/repsys/puxa_target.ecl PC: 19
##########################################################

**Comment by gtozzi** [comment]
@Skinny1001 it seems to be related to a packet hook. Has it happened again?

**Comment by Skinny1001** [comment]
Yes. It has happened again.

**Comment by gtozzi** [comment]
@Skinny1001 bugged packet hook scripts have the ability to crash the core. This is the most common crash scenario. The core shouldn't crash when something gets wrong on an hook script, but you can double-check your hook scripts to solve the problem meanwhile.

**Comment by gtozzi** [comment]
@Skinny1001 this should now be fixed in current git. A new beta will be out soon ;) Can you try it?

**Comment by Skinny1001** [comment]
@gtozzi I had disabled this specific script because it has only 4 lines of code and had not found a solution other than remove it. See the lines:

```
use uo;

program hook_target()
	return 1;
endprogram 

exported function puxa_target(who, byref packet)
	var is_FFA := GetObjProperty(who, "#FFA");
	if(is_FFA)	
		packet.SetString(7, "enemy", 1);
	endif
	return 0;
endfunction
```

Since you said that the bug was fixed, I will be reactivating the same and if a problem occurs, I will be reporting to you. Thank you for the feedback!

**Comment by Skinny1001** [comment]
The bug has been fixed.
