### ISSUE TITLE
Compiling on Windows with Visual Studio

### ISSUE THREAD

**Issue by Daviex** [polserver/polserver#71]
Hello.
I got a problem while compiling on Windows via VStudio 2017.
When I start the compiling, it just gvie a Linker error, after sometimes I found out that the Static Library for libcurl has a wrong name that the project can't find. In fact, into the folder, the DLL is called libcurl-d, while Visual Studio was looking for libcurl without the '-d'.

**Comment by turleypol** [comment]
Looks like curl was build as debug version. Remove the curl folder in libs and build pol in release mode.

**Comment by Daviex** [comment]
Mmmmh oh I see...
Yeah, indeed I was compiling via CMake with Debug instead of Release.
There's any difference between those two?

**Comment by turleypol** [comment]
Debug is for internal debugging, since it's slower it's not recommended to use it for shards.

**Comment by Daviex** [comment]
Oh, I got it. Thanks for the help. I will try again with Release and post it asap.

**Comment by Daviex** [comment]
Tested and now it goes really clear. Thanks for help.
